lib/game_store_web/router.ex
defmodule GameStoreWeb.Router do
  use GameStoreWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug GameStore.CurrentUser
  end

  scope "/", GameStoreWeb do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController, only: [:show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/games", GameController
  end

  # Other scopes may use custom stacks.
  # scope "/api", GameStoreWeb do
  #   pipe_through :api
  # end
end

lib/game_store_web/views/layout_view.ex
defmodule GameStoreWeb.LayoutView do
  use GameStoreWeb, :view
end

lib/game_store_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello GameStore!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
    <header class="header">
      <nav role="navigation">
        <ul class="nav nav-pills pull-right">
          <%= if @current_user do %>
            <li><%= @current_user.email %> (<%= @current_user.id %>)</li>
            <li>
              <%= link "Sign out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ul>
      </nav>
      <span class="logo"></span>
    </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>